= Indivuelle Reflexion
Emil Hempel

Meine Aufgaben haben sich im Projekt über mehrere Bereiche verteilt, fokussierten sich hauptsächlich aber auf den Entwurf, die Implementierung, und die Bereitstellung.

Den Entwurf der generellen Architektur des Backends sowie der REST API hatte ich bereits letztes Semester bearbeitet, besonders die API wurde aber nach Bedarf noch erweitert (hauptsächlich um das Invitesystem sowie einige erst vergessene Funktionen). Die Implementierung der Teile des Backends, für die ich zuständig war (REST API, Zusammenspiel mit dem Datenbankcode) war ebenfalls eine Weiterführung meiner Aufgaben aus dem letzten Semester. Für die Bereitstellung kam nun noch neben dem aktuell Halten der Dockercontainer noch das Betreiben einer Testinstanz hinzu. Tests habe ich für einige Teile meines Codes geschrieben, aber nicht für alles.
Desweiteren fielen zwischendurch noch gelegentlich weitere Aufgaben an, wie das Beheben von Merge-Konflikten, welche ignoriert wurden, oder die Fehlersuche, wenn die Software bei manchen Teammitgliedern erst nicht funktioniert hat.

Für den Entwurf der REST API habe ich mich an mir bereits bekannten Schnittstellen grob orientiert und anfangs für alle mir sinnvoll erscheinenden Funktionen Endpunkte angelegt. Festgehalten wurde das Design im OpenAPI-Dokument `docs/models/rest/api.yaml`. Ich hatte gelegentlich um Feedback zum Design von anderen Teammitgliedern gebeten, fehlende oder unklare Funktionen fielen meist auf, wenn diese vom Frontend benötigt wurden, teilweise aber auch bei der Implementierung anderer Funktionen. In dem Fall habe ich die API entsprechend erweitert.

Prinzipiell hat dieser Ansatz funktioniert, es wäre jedoch eventuell besser gewesen, vorher zu überlegen, welche Aktionen der Client eigentlich durchführt, um die API effizienter gestalten zu können. An einigen Stellen habe ich das beachtet, an anderen sind aber relativ viele Requests in schneller Abfolge nötig. 
Weiter habe ich zum Teil die Nutzersicht nicht ausreichend beachtet, weshalb es zum Beispiel aktuell noch nicht möglich ist, von über Nutzer-ID einen brauchbaren Nutzernamen zu bekommen. Dies wäre für eine sinnvolle Anzeige der WG-Mitglieder nötig gewesen, ist aber erst zu spät aufgefallen. Gemeinsames Design der API mit dem Frontendteam zusammen von Anfang an wäre vermutlich sinnvoll gewesen.


Den Entwurf des Backends habe ich in Textform in `docs/models/backend_general/backend.adoc` verfasst. Für die Wahl des Frameworks, Javalin, habe ich mich auf eine Empfehlung eines Freundes mit mehr Erfahrung verlassen. Mangels Erfahrung war dieser Entwurf noch nicht sonderlich genau und diente nur als grobe Orientierung, hat für diesen Zweck aber ausreichend gut Funktioniert. Die Schnittstelle zwischen meinem und Florians Code, welche ebenfalls Teil des Entwurfs war, wurde in dieser Form auch umgesetzt und hat mit einigen Erweiterungen gut funktioniert.


Die Implementierung der REST API war prinzipiell recht simpel. Pro Kategorie sind alle Endpunkte in einer Klasse zusammengefasst im Package `shareshop.rest`, um die Übersichtlichkeit zu bewahren. Request- und Responseobjekte sind separat im Package `shareshop.rest.requests`. Nach anfangs teils recht viel doppeltem Code habe ich diesen in die Klasse `RestUtils` ausgelagert, allerdings kein vollständiges Refactoring durchgeführt, dies wäre sinnvoll gewesen und der nächste Schritt in der Weiterentwicklung.  
Unit Tests für die API sind ebenfalls in die gleichen Kategorien unterteilt, zu finden unter `src/backend/src/test/java/shareshop/rest/`. Die Bereitstellung einer gemockten Testumgebung gestaltete sich hier leider als recht aufwändig, weshalb der Testumfang stark begrenzt ist. Von Anfang an die Testumgebung mitzuschreiben hätte hier zum einen den Zeitaufwand besser verteilt, zum anderen wahrscheinlich für besser strukturierten Code gesorgt. Die Tests so lange rauszuschieben, bis zu den entsprechenden Praktika, war nicht ideal. Manuelles Testen ist zwar möglich, und war auch die Variante der Wahl, stellt allerdings einen konstant hohen Aufwand dar und ist somit nur begrenzt praktikabel.


Das Erstellen der Dockercontainer und die Bereitstellung der Testinstanz liefen nach anfänglichen Unklarheiten wie mit dem Frontendcode zu verfahren ist, welche sich nach Rücksprache mit dem entsprechenden Teil des Teams geklärt hatten, weitgehend Problemlos. Einige Annahmen über die Startreihenfolger der Container führten auf anderen System erst zu Problemen, da die Abhängigkeiten nicht in `docker-compose.yml` spezifiziert waren, nach Finden des Problems war dieses aber einfach zu lösen. Ich konnte den Code anschließend einfach auf meinem Server herunterladen, die Ports und einen reverse Proxy entsprechend konfigurieren, und die Dockercontainer bauen und starten. 

