= Generelle Modellierung Backend

Das Backend lässt sich grob in 3 Teile unterteilen

- REST-API
- Datenbankanbindung
- Logik

Die REST-API und Datenbank sind hauptsächlich in anderen Dokumenten beschrieben, und die Datenbankanbindung ergibt sich großteils aus dem Datenbankmodell.

Logik und Datenbankanbindung lassen sich aktuell nicht ganz klar in separate Module trennen (zumindest finde ich dies nicht sinnvoll). Im weiteren Verlauf mit mehr Auswertungsfunktionen und mehr Verarbeitung der vorliegenden Daten sollte sich eine klarere Trennung im Code herausbilden, dies muss aber nicht separate Klassen bedeuten.


== 1. REST-API
Der Code für die REST-API muss unter den spezifizierten Endpoints die angegebenen Funktionen bereitstellen. Dabei werden in diesem Teil nur die nötigen Parameter entgegengenommen und so wie benötigt umgeformt, gegebenfalls Validiert oder bereinigt, und an die weiteren Teile des Backends weitergegeben. Die Ergebnisse werden (wenn es welche gibt) entsprechend serialisiert und zurückgegeben.  

Authentifizierung wird hier geprüft, die Implementierung davon erfolg aber in anderen Teilen (es werden dann also nur Aufrufe wie `getAuthorizedUser()` oder `Liste.userCanRead(user)` genutzt, oder einfach IDs verglichen).

Serialization und Deserialization wird mit `gson` umgesetzt. Dabei gibt es pro Objekt jeweils eine Klasse. Objekte, welche deserialisiert werden, haben zusätzlich eine Methode, um die Daten zu validieren. Respose-Objekte werden im Konstruktor befüllt.

=== Beispiel
Beispiel für `GET /wg/{wid}/list/{lid}` (weniger relevante Teile gekürzt)
----
public static void epGet(Context ctx) {
    Key<AppContext> ctxKey = new Key<AppContext>("Context");
    
    AppContext appCtx = (AppContext) ctx.appData(ctxKey);
    User usr = RestUtils.getAuthorizedUser(ctx);
    
    if(usr == null) {
        RestUtils.setResponseError(ctx, HttpStatus.UNAUTHORIZED, "not logged in");
        return;
    }
    
    UUID wgid = RestUtils.getPathParamUUIDSafe(ctx, "wid");
    
    try {
        if(!usr.isUserInWG(wgid)) {
            ...
            return;
        }
        
        WG wg = appCtx.wgManager.getWG(wgid);
        if(wg == null) {
            ...
            return;
        }
    
        ShoppingList slist = wg.getList(RestUtils.getPathParamUUIDSafe(ctx, "lid"););
        if(slist == null) {
            ...
            return;
        }
        
        ListContentResponse resp = new ListContentResponse(slist);
        
        Gson gson = new GsonBuilder().excludeFieldsWithoutExposeAnnotation().create();
        ctx.contentType(ContentType.JSON);
        ctx.result(gson.toJson(resp));
        ctx.status(HttpStatus.OK);
    } catch(SQLException e) {
        ...
    }
}
----

== 2. Datenbankanbindung
Nach aktuellem Stand ist die Datenbankanbindung nicht wirklich von der Logik getrennt, sondern wird in diese eingebaut (zum aktuellen Stand ist das Ergebnis ähnlich einem ORM).

Falls eine Trennung trotzdem gewünscht ist, würde dies erstmal viel doppelten Code bedeuten (getter und setter, sowie create und remove für die jeweiligen Objekte). Im späteren Verlauf kann dies sinnvoll sein, muss es aber nicht (hauptsächlich nur, wenn bei der verwendeten Datenbank mehr Flexibilität nötig ist).

== 3. Logik
Der Logiklayer umfasst alles zwischen der Datenbank und der REST-API.

Die angegebenen Funktionen sind nur ein Überblick darüber, was die Klassen können müssen und stellen keine genaue Schnittstelle dar, sollten aber als grobe Orientierung dienen. Es können in der Implementierung auch, wenn es sich anbietet, mehrere Funktionen in einer vereint werden, oder (wahrscheinlicher) eine Funktion auf mehrere aufgeteilt werden. Zur Veranschaulichung werden sie hier aber wie Methoden gehandhabt.
Properties werden nur angegeben, wenn diese nicht anderweitig (z.B. aus der DB) einfach ersichtlich sind.

Um generelle Anforderungen an Klassen anzuzeigen werden Tags zugewiesen:

- `DB`: Klasse kommuniziert mit der Datenbank

=== UserManager
Verwaltet Nutzer. Unterstützt Aktionen, bei welchen noch kein Handle für den User vorliegt. Alles andere wird direkt über den User gemacht.

==== benötigte Funktionen
- `create`
- `login`
- `getUser`

==== Tags
- `DB`

=== User
Klasse, welche einen Nutzer repräsentiert.

==== benötigte Funktionen
- `remove`
- `set...` (umfasst alle Änderungen, die an dem Nutzer vorgenommen werden können. Aufspalten!)
- `get...` Informationen abfragen (zugehörige WGs, verschiedener Status)

==== Tags
- `DB`

=== WGManager

==== Funktionen
- `create`
- `getWG`

==== Tags
- `DB`

=== WG
TODO: WG-spezifische Nutzerinformationen könnten entweder über `User` oder `WG` abgefragt werden, `WG` ist m.M.n sinnvoller. Aktuell gibt es außer Nutzerzugehörigkeit und Berechtigungen noch keine.

==== Funktionen
- `set...`
- `get...`
- `hasUser` (Nutzerzugehörigkeit prüfen, ggf. noch auf weitere Permissions ausweiten wie RO-Nutzer, Admins)
- `getList`
- `createList`
- `remove`
- `addUser`
- `removeUser`
- lists irgendwie enumerable

==== Tags
- `DB`

=== ShoppingList

==== Funktionen
- `set...`
- `get...`
- `getCurrentList` (aktueller Stand der Liste)
- `getListLog`  (Änderungen, ideal noch mit pagination)
- `updateCache` (Änderungen auf gecachten Zustand übertragen, erst sinnvoll, wenn die Änderungsliste geführt wird, aktuell nicht genutzt)
- `addChange(user, change...)` (Listenänderung eintragen)
- `remove`

==== Tags
- `DB`

=== ItemManager

==== Funktionen
- `createItem(WG)`
- `getItem(id)`
- `search(wg, query) -> Item[]`

==== Tags
- `DB`

=== Item

==== Funktionen
- `get...`
- `set...`
- `remove`

==== Tags
- `DB`
