# 
upstream backend_upstream{
    server backend:8001;
    keepalive 10;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # API proxy. This can be removed if it's not needed
    # (for example, if proxying is handled outside these containers.
    # The API path configuration of the frontend needs to be adjusted accordingly)

    location /api/ {
        proxy_intercept_errors on;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://backend_upstream/;
    }
}