= Projektplan: ShareShop

* Benjamin Banse Benjamin.Banse@stud.htw-dresden.de
* Kevin Bürger Bürger.Kevin@stud.htw-dresden.de
* Anni Nguyen Anni.Nguyen@stud.htw-dresden.de
* Emil Hempel Emil.Hempel@stud.htw-dresden.de
* Valencia Melvika Valencia.Melvika@stud.htw-dresden.de
* Florian Süßmann Florian.Süßmann@stud.htw-dresden.de
* Han Nguyen HanNguyen@stud.htw-dresden.de

2025-05-29
include::../_includes/default-attributes.inc.adoc[]


== Einführung
In diesem Dokument werden die Abläufe rund um das Projekt beschrieben. Teil davon sind unter anderem Terminplanung, Sprint-Details und Vorgaben zur Ticketgestaltung.


== Projektorganisation

=== Teammitglieder
[cols="1,2", options="header"]
|===
| Name           | Rolle

| Benjamin Banse  | Projektleiter, Scrum Master
| Anni Nguyen     | Front-End Leader, Front-End Developer
| Kevin Bürger    | Product Owner, Dokumentation
| Emil Hempel     | Back-End Developer
| Valencia Melvika| Front-End Developer
| Florian Süßmann | Back-End Developer
| Han Nguyen      | Front-End Developer
|===

=== Termine
* **Dailies**:
** Dienstags: 18:30 Uhr – 19:00 Uhr (Pflicht)
** Donnerstags: 20:30 Uhr – 21:00 Uhr (Freiwillig)

* **Sprint-Planning**:
** Immer mittwochs vor Sprintbeginn, Zeit wird flexibel im Team abgestimmt (z. B. 21.05.2025, 17:00 Uhr)

* **Sprint-Review**:
** Voraussichtlich 01.06.2025, je nach Wireframe-Fortschritt und Kundentermin

* **Sprint-Retrospektive**:
** Jeweils freitags, eine Woche vor Sprint-Ende, 14:00 Uhr – 15:00 Uhr
** Erste Retro fand am 16.05.2025 statt (Meeting 09)


== Praktiken und Bewertung

=== Sprint-Taktiken
Wir arbeiten im vierwöchigen Sprint-Zyklus. Das Team nutzt ein gemeinsames Kanban-Board mit Review-Spalte, um Fortschritt und Codequalität sichtbar zu machen. Neben GitHub nutzen wir Figma und Miro zur UI-Modellierung und kollaborativen Designarbeit.

=== Definition of Ready
* Das Ticket ist klar und verständlich formuliert.
* Akzeptanzkriterien sind enthalten.
* Storypoints wurden geschätzt (z. B. 6h = 6 SP-Regel).
* Keine offenen Blocker oder Abhängigkeiten.
* Umfang ist für eine Person in einem Sprint machbar.
* Freigabe oder Absprache mit dem PO erfolgte.
* Alle nötigen Infos und Anhänge liegen bei.

=== Definition of Done
* Code ist vollständig und korrekt implementiert.
* Alle Akzeptanzkriterien sind erfüllt.
* Unit-Tests vorhanden und erfolgreich.
* Manuelles Testing (v. a. Front-End) abgeschlossen.
* Code Review erfolgt und freigegeben.
* Doku wurde angepasst/aktualisiert.
* Änderung ist in Testumgebung deployed.
* Abnahme durch PO ist erfolgt.

== Deployment (bereitstellung der Software)

Aktuell arbeiten wir daran, unsere Software so vorzubereiten, dass sie einfach gestartet und genutzt werden kann. 
Das für uns im Team als auch später für andere.

Folgende Schritte haben wir bereits unternommen:

* **Datenbank vorbereiten**: Florian hat eine Test-Datenbank erstellt und ein Skript entwickelt, mit dem diese Datenbank automatisch eingerichtet werden kann. Das bedeutet, dass niemand die Datenbank manuell einrichten muss; das Skript übernimmt das für uns.

* **Automatischer Start der Anwendung**: Wir planen, unsere Anwendung so zu verpacken, dass sie mit einem einzigen Befehl gestartet werden kann. Dafür nutzen wir ein Tool namens Docker. Es sorgt dafür, dass alle benötigten Teile der Anwendung zusammenarbeiten und auf jedem Computer gleich funktionieren.

Unser Ziel ist es, dass jeder im Team (und später auch andere Nutzer) die Anwendung problemlos starten und verwenden kann, ohne sich um technische Details kümmern zu müssen.

== Erkenntnisse (Lessons Learned)

* Zwei Pflicht-Dailies pro Woche waren zunächst zu viel – Donnerstagstermin wurde als freiwillig deklariert.
* Das frühzeitige Definieren von Branching- und Pull-Request-Standards war sinnvoll zur Qualitätssicherung.
* Modellierung ist essenziell für gute Sprintplanung – besonders beim Backend hilfreich für Ticketdefinition.
* Storypoints helfen bei realistischeren Aufwandseinschätzungen, müssen aber noch stärker im Team verankert werden.
* Die Dokumentation (Adoc-Struktur) braucht klare Rollenverteilung – PO und Entwicklerteams strukturieren Backend/Frontend getrennt.

