= Projektplan: ShareShop

* Benjamin Banse benjamin.banse@stud.htw-dresden.de
* Kevin Bürger kevin.bueger@stud.htw-dresden.de
* Anni Nguyen anni.nguyen@stud.htw-dresden.de
* Emil Hempel emil.hempel@stud.htw-dresden.de
* Valencia Melvika valencia.melvika@stud.htw-dresden.de
* Florian Süßmann florian.suessmann@stud.htw-dresden.de
* Han Nguyen huyenbaohan.nguyen@stud.htw-dresden.de

2025-05-29
include::../_includes/default-attributes.inc.adoc[]


== Einführung
In diesem Dokument werden die Abläufe rund um das Projekt beschrieben. Teil davon sind unter anderem Terminplanung, Sprint-Details und Vorgaben zur Ticketgestaltung.


== Projektorganisation

=== Teammitglieder
[cols="1,2", options="header"]
|===
| Name           | Rolle

| Benjamin Banse  | Projektleiter, Scrum Master
| Anni Nguyen     | Front-End Leader, Front-End Developer
| Kevin Bürger    | Product Owner, Dokumentation
| Emil Hempel     | Back-End Developer
| Valencia Melvika| Front-End Developer
| Florian Süßmann | Back-End Developer
| Han Nguyen      | Front-End Developer
|===

=== Termine
* **Dailies**:
** Dienstags: 18:30 Uhr – 19:00 Uhr (Pflicht)
** Donnerstags: 20:30 Uhr – 21:00 Uhr (Freiwillig)

* **Sprint-Planning**:
** Immer mittwochs vor Sprintbeginn, Zeit wird flexibel im Team abgestimmt (z. B. 21.05.2025, 17:00 Uhr)

* **Sprint-Review**:
**Hat stattgefunden am 15.06.2025, Feedback wurde in Tickets umgewandelt, konnte jedoch für den Prototypen aus zeitlichen Gründen nicht mehr umgesetzt werden.

* **Sprint-Retrospektive**:
** Jeweils freitags, eine Woche vor Sprint-Ende, 14:00 Uhr – 15:00 Uhr
** Erste Retro fand am 16.05.2025 statt (Meeting 09)
** Zweite Retro fand am 20.06.2025 statt


== Praktiken und Bewertung

=== Sprint-Taktiken
Wir arbeiten im vierwöchigen Sprint-Zyklus. Das Team nutzt ein gemeinsames Kanban-Board mit Review-Spalte, um Fortschritt und Codequalität sichtbar zu machen. Neben GitHub nutzen wir Figma und Miro zur UI-Modellierung und kollaborativen Designarbeit.

=== Definition of Ready
* Das Ticket ist klar und verständlich formuliert.
* Akzeptanzkriterien sind enthalten.
* Storypoints wurden geschätzt (z. B. 6h = 6 SP-Regel).
* Keine offenen Blocker oder Abhängigkeiten.
* Umfang ist für eine Person in einem Sprint machbar.
* Freigabe oder Absprache mit dem PO erfolgte.
* Alle nötigen Infos und Anhänge liegen bei.

=== Definition of Done
* Code ist vollständig und korrekt implementiert.
* Alle Akzeptanzkriterien sind erfüllt.
* Unit-Tests vorhanden und erfolgreich. (Für Prototypen erstmalig nicht so wichtig)
* Manuelles Testing (v. a. Front-End) abgeschlossen.
* Code Review erfolgt und freigegeben.
* Doku wurde angepasst/aktualisiert.
* Änderung ist in Testumgebung deployed.
* Abnahme durch PO ist erfolgt.

== Deployment (bereitstellung der Software)

Die Software wird auf einem Server deployed, zu welchem der Betreiber Zugang erhält. Nutzer können sich dann über eine gewählte URL mit der App kommunizieren und sie verwenden.

Die Software unterteilt sich momentan noch in einzelne Docker-Container, welche untereinander Kommunizieren. Für den momentan Stand reicht dieses Deployment vollkommen aus.
Sobald die Software jedoch in eine Live-Umgebung wechselt (also für Kunden sichtbar), so müsste eine andere Methode fürs Deployment gesucht werden, da sonst der Traffic für die Docker-Container zu groß wäre.
Für die Produktiv/Live-Umgebung werden wir wahrscheinlich auf Docker-Swarm zurückgreifen, da man damit sein Produkt skalierbar anhand des Traffics ausrollen kann.

== Erkenntnisse (Lessons Learned)

=== Erkenntnisse aus SE1
* Zwei Pflicht-Dailies pro Woche waren zunächst zu viel – Donnerstagstermin wurde als freiwillig deklariert.
* Das frühzeitige Definieren von Branching- und Pull-Request-Standards war sinnvoll zur Qualitätssicherung.
* Modellierung ist essenziell für gute Sprintplanung – besonders beim Backend hilfreich für Ticketdefinition.
* Storypoints helfen bei realistischeren Aufwandseinschätzungen, müssen aber noch stärker im Team verankert werden.
* Die Dokumentation (Adoc-Struktur) braucht klare Rollenverteilung – PO und Entwicklerteams strukturieren Backend/Frontend getrennt.
* Als ProjektOwner/Scrum-Master muss man aktiv auf seine Kollegen zugehen - Fragen werden damit schneller geklärt.
* Code-Spezifikationen wie Schreibweise (CamelCase oder snake_case) sowie die Strukturierung und Namensgebung von Ordner und Dateien sollte wenn möglich bereits zu Beginn des Projektes festgehalten sein, damit NameErrors nicht passieren und der Code strukturiert bleibt.
* Die Aufteilung des Teams in einzelne Unterteams war zwar anfangs effektiv, jedoch hat sich zum Ende des 1. Semesters gezeigt, dass die Kommunikation bzw. auch die Kompetenz gefehlt hat, um die jeweiligen Fachgebiete wieder zusammen zu führen. Hier hätte man für mehr Kommunikation sorgen sollen, sodass beide Teams wissen, wie die Verbindung gebaut werden kann.

=== Erkenntnisse aus SE2
* Fehlendes Sprint-Planning hat dazu geführt, dass Unklarheiten der Themen entstanden sind und die Work-Balance zwischen den beiden Sub-Teams sehr schlecht war.
* Die Einführung eines PR-Kanals in Discord hat das Problem der dauerhaft-offenen Pull-Requests deutlich verringert.
* Die Einhaltung von "Definition of Done" hätte uns einiges an Problemen in der Sturktur als auch in Merge-Conflicts erspart.
* Ohne gute Vorbereitung und Alternativen Kommunikationswegen war es schwierig, in 2 verschiedenen Zeitzonen miteinander zu arbeiten
* Automatisierte Github-Checks hätten uns bei sturkturellen Problemen (Einhaltung der Code-Richtlinien) geholfen.
* Innere Reviews haben kleinere Bugs vorgehoben, welche sonst untergegangen werden.
* Retrospektiven haben geholfen, Probleme anzusprechen und dementsprechende Lösungen auszuprobieren.

== Risiken während der Entwicklung

Es gibt während der Entwicklungszeit auch Risiken, mit der man im Team rechnen muss und welche man auch bewältigen muss,
ohne dabei die Effektivität des Teams bzw. der Entwicklung einzuschränken.

* Krankheitsausfall:
** Gegenmaßnahme/Umgang: Bei Krankheitsbedingtem Ausfall muss man durch Vertretungsregelung, Wissensdokumentation oder Pufferzeiten gegensteuern. Da Eine Vertretung in einem solch kleinen Team jedoch schwer realisierbar ist, sprechen die anderen beiden Punkte mehr auf das Ziel an.

* Zeitdruck:
** Gegenmaßnahme/Umgang: Bei Zeitdruck muss die Aufwandsschätzung neu überarbeitet werden, damit sich Altlasten nicht über mehrere Sprints ziehen. Das sorgt für Zeitdruck innerhalb des Teams. Auch regelmäßige Status-Abfragen können dazu beitragen, solche Krisen frühzeitig zu erkennen.

* Inhaltliche Unklarheit:
** Gegenmaßnahme/Umgang: Bei diesem Risiko muss man eine gute Balance zwischen Absprachen in Dailies, Wissensdokumentation als auch klare Anforderungsdefinitionen finden. Je besser die Tickets vorher besprochen (bspw. in Plannings) wurden, desto besser sind die inhaltlichen Anforderungen und desto geringer ist das Risiko inhaltlich festzustecken.

* Technische Risiken:
** Gegenmaßnahme/Umgang: Man kann das Risiko, an einer unreifen Technologie festzustecken, verhindern, indem man vorher Machbarkeitsanalysen durchführt. Diese können anhand eines Prototypen oder genauerer Recherche absolviert werden.

* Rechtliche Risiken:
** Gegenmaßnahme/Umgang: Sollte sich etwas an den Gesetzen durch den Gesetzesgeber ändern, so sollte man möglichst schnell handeln und jeglichste Themen, welche damit zu tun haben, gut dokumentieren. So kann später schneller und effektiver gehandelt werden.

== Links
* GitHub Sprint-Backlog:
** https://github.com/users/MasterOfDevilLP/projects/3/views/1
* GitHub Product-Backlog:
** https://github.com/users/MasterOfDevilLP/projects/3/views/6
* Miro
** https://miro.com/app/board/uXjVIEsf25w=/
